
- name: Adding Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create new directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract the content
  ansible.builtin.unarchive:
          src: https://roboshop-artifacts.s3.amazonaws.com/{{ app_name }}-v3.zip
          dest: /app
          remote_src: yes

