
  -  name: Disable default nginx
     ansible.builtin.shell: dnf module disable nginx -y

  -  name: Enable Nginx 24 Version
     ansible.builtin.shell: dnf module enable nginx:1.24 -y

  -  name: Install nginx
     ansible.builtin.dnf:
      name: nginx
      state: present

  - name: copy nginx config file
    ansible.builtin.template:
     src: nginx.conf
     dest: /etc/nginx/nginx.conf

  - name: start nginx
    ansible.builtin.systemd_service:
     name: nginx
     state: started


       #source common.sh
       #component=frontend
       #app_path=/usr/share/nginx/html
       #
       #
       #PRINT Disable Nginx default Version
       #dnf module disable nginx -y  &>>$LOG_FILE
       #STAT $?
       #
       #PRINT Enable Nginx 24 Version
       #dnf module enable nginx:1.24 -y  &>>$LOG_FILE
       #STAT $?
       #
       #PRINT Install Nginx
       #dnf install nginx -y  &>>$LOG_FILE
       #STAT $?
       #
       #PRINT Copy nginx config file
       #cp nginx.conf /etc/nginx/nginx.conf  &>>$LOG_FILE
       #STAT $?
       #
       #APP_PREREQ
       #
       #PRINT Start Nginx Service
       #systemctl enable nginx  &>>$LOG_FILE
       #systemctl restart nginx  &>>$LOG_FILE
      #STAT $?