- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Install mysql
  ansible.builtin.dnf:
   name: mysql-server
   state: installed

- name: Start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: yes

- name: Setup MySQL Root Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
